### ISSUE TITLE
fortinet parser

### ISSUE THREAD

**Issue by dr4gon123** [empow/logstash-parsers#1]
regarding [fortinet ips parser](https://github.com/empow/logstash-parsers/blob/master/parsers/fortinet/fortinet.conf), you can benefit from [fortinet translation to ecs](https://github.com/elastic/ecs/issues/492)

**Comment by hyperbaba** [comment]
or : https://github.com/enotspe/fortinet-2-elasticsearch. It idea looks very similar to this project 
Oh, i just noticed that OP was project owner :)

**Comment by zez3** [comment]
I think this can be closed since they merged the PR as filbeat module in v7

https://github.com/elastic/beats/pull/18254
